### ISSUE TITLE
入库出库记录查询界面 无法显示出库记录

### ISSUE THREAD

**Issue by qinghe** [GOD-FUKUOKA/GODInventory#12]
在出库界面登记出库记录后，提示成功登记。但在入库出库记录查询界面，只能显示入库记录，无论怎么修改条件都无法显示出库记录
1. 添加 t_stockrec.厂家，  出入库时设置 对应值
2. 添加 所有厂家 条件。
3. 入库出库记录修正无法显示出库

**Comment by Lewishui** [comment]
@qinghe  OK
