### ISSUE TITLE
Fax 订单添加

### ISSUE THREAD

**Issue by qinghe** [GOD-FUKUOKA/GODInventory#4]
需要手工输入的是，店番（店名和法人コード及客户名称自动适配上屏），
部门コード（目前我们的产品都是第9部门，将来可能会有其它部门商品）需要自己输入
発注日和納品希望日也需要输入
納品場所，需要根据店番，确定该店是否有多个納品場所，如果有，就给出选项，并自动适配納品場所番号
然后就是具体商品内容了
伝票番号是自动编号的，発注形態要选择，最好默认是“補充“
JANコード和商品コード，输入任何一个都可以自动适配上屏相对应的商品名称
以及规格和原单价、卖单价
但也应该允许手动编辑名称、规格、元单价和卖单价
最后是受注数，也就是订货数量
画面上方的仕入先コード“249706”和出荷業務仕入先コード“249706”以及我司名称都是固定的，所以没必要手工输入
同一个画面上应该不限制允许输入的订单条数，但输入的每一条订单都应该有一个自动编号的伝票番号
另外，発注形態没必要每一行都去单独确定，当然保留每一行单独确定的功能也可以，但最好能有一个一次性修改所有订单的発注形態的功能

**Comment by qinghe** [comment]
关于传票番号的说明
fax传票番号，参考ナフコEDIデータ送受信説明書.pdf 第44页，共8位，第1、2位为0，之后是5位数字，从00001到99999，我们现在用的那个软件，是按照各个店，分别从00001开始
比如店番001的店铺，他的fax订单编号就是从00001开始，逐条增加
店番002也是从00001开始
要求3个月之内不许重复
实际上每家店一个月理论上最多也就是不到1000条订单，所以就一直用到99999，然后再重新开始就好
还有第8位，是校验位，计算方法是7DR
也就是之前5位，各位数字的和，除以7，余数就是校验位的数值
如果是 第十个订单：即 00010， 直接除以7，取余数为3， 传票番号为： 00000103
如果刚好能够除尽，校验位就为0

**Comment by qinghe** [comment]
1. 显示字段列表
   传票番号  | 发注形态 | JANCode | 商品Code | 商品名 | 规格 | 原单价 | 买单价 | 受注数
2. 每行后面有删除按钮
3. 可以修改发注形态， 其为选项列表
4. 新建订单需要录入项目请参考截图
   @Lewishui

**Comment by Lewishui** [comment]
納品場所，需要根据店番，确定该店是否有多个納品場所，如果有，就给出选项，并自动适配納品場所番号然后就是具体商品内容了   ----可有建成的表？ 还是新建 ，表结构 主key 叫什么

**Comment by qinghe** [comment]
@Lewishui  没有建成的表，需要新建表， t_locations。
表结构定义如下：
Id
店舗コード int
納品場所コード  int
納品場所名カナ  varchar64
納品場所名漢字 varchar64
納品場所名略称 varchar64

Id  主键，自增
店舗コード+納品場所コード  唯一

**Comment by qinghe** [comment]
列表显示字段如下：
伝票番号,発注形態,雑コード,商品コード,ジャンル,商品名,規格,JANコード,原単価,売単価,ロット,口数,受注数
