### ISSUE TITLE
商品分类和 工厂 是对应的

### ISSUE THREAD

**Issue by qinghe** [GOD-FUKUOKA/GODInventory#9]
手推车商品 工厂是 青岛华天

碎石商品的默认工厂是”自社工場“

水泥制品商品的默认工厂是”興和日東“

水泥制品还有一家工厂是“ランデス”

**Comment by qinghe** [comment]
@Lewishui  入库界面已做好

**Comment by Lewishui** [comment]
@qinghe  ok  其他界面已完善
